services:
  - type: web
    name: promptfolio-backend
    env: node
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: BYTEZ_API_KEY
        sync: false
